<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="5.0.0-rc.5-26219.1" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="5.0.0-rc.5-26219.1" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="5.0.0-rc.5-26219.1" />
		<PackageReference Include="Mapster" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.4" />
	</ItemGroup>
</Project>
